services:
    form.type.entity_identifier:
        class: 'Avro\ExtraBundle\Form\Type\EntityIdentifierType'
        tags:
            - { name: form.type, alias: entity_id }
        arguments: ["@doctrine.odm.mongodb.document_manager"]

    form.type.dynamic_entity:
        class: 'Avro\ExtraBundle\Form\Type\DynamicEntityType'
        tags:
            - { name: form.type, alias: dynamic_entity }
        arguments: ["@doctrine.odm.mongodb.document_manager"]

