services:
    avro_extra.securityContextUser.param_converter:
        class: Avro\ExtraBundle\Request\ParamConverter\SecurityContextUser
        arguments: ["@security.context"]
        tags:
            - {name: request.param_converter, converter: user, priority: 10}
